/* Generated Event bindings (stub) */
#pragma once

// Types discovered in registry snapshot:
// EventType::SDL_Event
// EventType::OnRender
// EventType::OnUpdate
// EventType::OnQuit
// EventType::ClipboardPaste
// EventType::TimerComplete
// EventType::TimerCycleComplete
// EventType::TimerStop
// EventType::Drop
// EventType::Dragging
// EventType::Hidden
// EventType::EnterFrame
// EventType::Disabled
// EventType::Drag
// EventType::SelectionChanged
// EventType::MouseButtonUp
// EventType::MouseButtonDown
// EventType::Visible
// EventType::FocusLost
// EventType::KeyUp
// EventType::AddedToStage
// EventType::RemovedFromStage
// EventType::OnEvent
// EventType::TimerTick
// EventType::KeyDown
// EventType::StageClosed
// EventType::ClipboardCopy
// EventType::Added
// EventType::MouseMove
// EventType::LeaveFullscreen
// EventType::Quit
// EventType::None
// EventType::StageOpened
// EventType::MouseClick
// EventType::User
// EventType::OnInit
// EventType::Removed
// EventType::StateChanged
// EventType::MouseDoubleClick
// EventType::MouseEnter
// EventType::OnPreRender
// EventType::FocusGained
// EventType::TimerPause
// EventType::TimerStart
// EventType::Hide
// EventType::TextInput
// EventType::Resize
// EventType::ValueChanged
// EventType::MouseLeave
// EventType::Move
// EventType::Enabled
// EventType::MouseWheel
// EventType::EnterFullscreen
// EventType::Show
