/* Generated by SDOM CBindingGenerator */
#ifndef SDOM_CAPI_OBJECTS_GENERATED_H
#define SDOM_CAPI_OBJECTS_GENERATED_H

#define SDOM_CAPI_GENERATED_MAJOR 0
#define SDOM_CAPI_GENERATED_MINOR 5
#define SDOM_CAPI_GENERATED_PATCH 181
#define SDOM_CAPI_GENERATED_VERSION_STRING "0.5.181"

#ifdef __cplusplus
extern "C" {
#endif

typedef void* sdom_handle_t;

/* Type: UT_TestType */
typedef struct UT_TestType_t* UT_TestType_handle;
sdom_handle_t sdom_create_UT_TestType(void);
void sdom_destroy_UT_TestType(sdom_handle_t);

/* Exported C API function prototypes (generated) */
#ifdef __cplusplus
}
#endif

#endif // SDOM_CAPI_OBJECTS_GENERATED_H
