/**
 * @file SDOM_CAPI_Events.h
 * @brief Stable C API enumeration of SDOM EventType values.
 *
 * This header is autogenerated by the SDOM CBindingGenerator from the
 * project's `DataRegistry` metadata. It provides stable numeric IDs for
 * all known `EventType` values and inline documentation for each entry.
 *
 * @since SDOM 0.5
 * @note AUTOGENERATED - DO NOT EDIT. Regenerate with the repository's
 *       `dataregistry_generator` when event metadata changes.
 */        
#pragma once

/* Common C API (error codes, free helper) */
#include <SDOM/CAPI/SDOM_CAPI_Common.h>

/* Include generated objects header (must be on include path) */
#include "sdom_capi_objects_generated.h"

#include <stdint.h>
#include <stddef.h>

/* Opaque handle types */
typedef struct SDOM_EventTypeHandle_ *SDOM_EventTypeHandle;
typedef struct SDOM_EventHandle_ *SDOM_EventHandle;

/* EventType descriptor: common stable fields plus extensible JSON */
struct SDOM_EventTypeDesc {
    const char *name; /* display / canonical name */
    uint32_t id; /* SDOM_EventTypeId (numeric id) */
    const char *category; /* category/grouping */
    const char *doc; /* short documentation string */
    const char *metadata_json; /* optional JSON for extensible fields (nullable) */
    void *user_data; /* reserved for callers */
};

#ifdef __cplusplus
extern "C" {
#endif

/* Paired generic APIs for EventType */
SDOM_EventTypeHandle SDOM_CreateEventType(const struct SDOM_EventTypeDesc *desc);
int SDOM_GetEventTypeDesc(SDOM_EventTypeHandle h, struct SDOM_EventTypeDesc *out);
int SDOM_UpdateEventType(SDOM_EventTypeHandle h, const struct SDOM_EventTypeDesc *desc);
void SDOM_DestroyEventType(SDOM_EventTypeHandle h);
SDOM_EventTypeHandle SDOM_FindEventTypeByName(const char *name);
size_t SDOM_EnumEventTypes(size_t index, SDOM_EventTypeHandle *out); /* iterate by index */

/* Event descriptor: payload is represented as JSON for extensibility */
struct SDOM_EventDesc {
    uint32_t type_id; /* EventType numeric id */
    const char *name; /* optional event name */
    const char *payload_json; /* optional JSON payload (nullable) */
    void *user_data; /* reserved for callers */
};

/* Paired generic APIs for Events */
SDOM_EventHandle SDOM_CreateEvent(const struct SDOM_EventDesc *desc);
int SDOM_GetEventDesc(SDOM_EventHandle h, struct SDOM_EventDesc *out);
int SDOM_UpdateEvent(SDOM_EventHandle h, const struct SDOM_EventDesc *desc);
void SDOM_DestroyEvent(SDOM_EventHandle h);
int SDOM_SendEvent(SDOM_EventHandle h);

typedef uint32_t SDOM_EventTypeId;

/** @defgroup SDOM_EventMacros Event Macros
 *  Helpers for extracting category/index from event IDs.
 *  @{ */
// Helpers to extract category and index from an event id:
#define SDOM_EVENT_CATEGORY(id) (((uint32_t)(id)) >> 8)
#define SDOM_EVENT_INDEX(id) (((uint32_t)(id)) & 0xFFU)

/** @} */

/** @defgroup SDOM_EventTypeIDs SDOM EventType IDs
 *  @brief Autogenerated ID constants for all SDOM EventTypes.
 *  @{ */
/** @ingroup SDOM_EventTypeIDs */
typedef enum SDOM_EventType {

    /* Core -------------------------------------------------------------- */
    SDOM_EVENT_FIRST = 0x0000,               /**< Reserved (do not use) */
    SDOM_EVENT_QUIT = 0x00000001,            /**< Signals that the application or main stage is closing. Global only. */
    SDOM_EVENT_NONE,                         /**< A general-purpose EventType for testing or to represent a non-event. */

    /* Application -------------------------------------------------------------- */
    SDOM_EVENT_ADDED = 0x00000100,           /**< Dispatched when an object is added as a child to another display object. */
    SDOM_EVENT_REMOVED,                      /**< Dispatched when an object is removed from its parent container. */
    SDOM_EVENT_ADDED_TO_STAGE,               /**< Emitted when an object becomes part of the active stage hierarchy. */
    SDOM_EVENT_REMOVED_FROM_STAGE,           /**< Emitted when an object is detached from the stage hierarchy. */
    SDOM_EVENT_STAGE_OPENED,                 /**< Indicates that a new stage or window has been opened and initialized. */
    SDOM_EVENT_STAGE_CLOSED,                 /**< Indicates that a stage or window has been closed and destroyed. */

    /* Input -------------------------------------------------------------- */
    SDOM_EVENT_KEY_DOWN = 0x00000200,        /**< Keyboard key pressed down; bubbles through active hierarchy. */
    SDOM_EVENT_KEY_UP,                       /**< Keyboard key released; bubbles through active hierarchy. */
    SDOM_EVENT_TEXT_INPUT,                   /**< Text input event carrying UTF-8 text from the input system. */
    SDOM_EVENT_MOUSE_BUTTON_DOWN,            /**< Mouse button pressed on a target object. */
    SDOM_EVENT_MOUSE_BUTTON_UP,              /**< Mouse button released over a target object. */
    SDOM_EVENT_MOUSE_WHEEL,                  /**< Mouse wheel scrolled; carries wheel delta values. */
    SDOM_EVENT_MOUSE_MOVE,                   /**< Mouse moved within or over a target object (target-only). */
    SDOM_EVENT_MOUSE_CLICK,                  /**< Mouse button clicked (press + release) on a target object. */
    SDOM_EVENT_MOUSE_DOUBLE_CLICK,           /**< Mouse double-clicked on a target object. */
    SDOM_EVENT_MOUSE_ENTER,                  /**< Pointer entered the bounds of an object; bubbles for hover tracking. */
    SDOM_EVENT_MOUSE_LEAVE,                  /**< Pointer left the bounds of an object; bubbles for hover tracking. */

    /* Window -------------------------------------------------------------- */
    SDOM_EVENT_FOCUS_GAINED = 0x00000300,    /**< The window or stage gained input focus. */
    SDOM_EVENT_FOCUS_LOST,                   /**< The window or stage lost input focus. */
    SDOM_EVENT_RESIZE,                       /**< Window or stage resized; width and height values updated. */
    SDOM_EVENT_MOVE,                         /**< Window or stage moved; position values updated. */
    SDOM_EVENT_SHOW,                         /**< Window or object became visible on screen. */
    SDOM_EVENT_HIDE,                         /**< Window or object hidden from view. */
    SDOM_EVENT_ENTER_FULLSCREEN,             /**< Application entered fullscreen mode. */
    SDOM_EVENT_LEAVE_FULLSCREEN,             /**< Application exited fullscreen mode. */

    /* UI -------------------------------------------------------------- */
    SDOM_EVENT_VALUE_CHANGED = 0x00000400,   /**< Value of a control or property has changed. */
    SDOM_EVENT_STATE_CHANGED,                /**< UI element or component state changed (e.g., active, toggled). */
    SDOM_EVENT_SELECTION_CHANGED,            /**< User selection or highlight changed within a list or group. */
    SDOM_EVENT_ENABLED,                      /**< Object or control has been enabled and can now receive input. */
    SDOM_EVENT_DISABLED,                     /**< Object or control has been disabled and can no longer receive input. */
    SDOM_EVENT_VISIBLE,                      /**< Object became visible within its parent hierarchy. */
    SDOM_EVENT_HIDDEN,                       /**< Object became hidden within its parent hierarchy. */

    /* DragAndDrop -------------------------------------------------------------- */
    SDOM_EVENT_DRAG = 0x00000500,            /**< Dragging in progress; position updated while dragging. */
    SDOM_EVENT_DRAGGING,                     /**< Continuous drag event emitted while dragging is active. */
    SDOM_EVENT_DROP,                         /**< An item or data payload was dropped onto a valid target. */

    /* Timer -------------------------------------------------------------- */
    SDOM_EVENT_TIMER_START = 0x00000600,     /**< Timer started or resumed counting. */
    SDOM_EVENT_TIMER_STOP,                   /**< Timer stopped and reset to initial state. */
    SDOM_EVENT_TIMER_PAUSE,                  /**< Timer paused but not reset. */
    SDOM_EVENT_TIMER_TICK,                   /**< Timer tick event; emitted on each interval step. */
    SDOM_EVENT_TIMER_CYCLE_COMPLETE,         /**< Timer completed one full interval cycle. */
    SDOM_EVENT_TIMER_COMPLETE,               /**< Timer finished all cycles and has reached completion. */

    /* Clipboard -------------------------------------------------------------- */
    SDOM_EVENT_CLIPBOARD_COPY = 0x00000700,  /**< Data copied to the system clipboard. */
    SDOM_EVENT_CLIPBOARD_PASTE,              /**< Data pasted from the system clipboard. */

    /* Listener -------------------------------------------------------------- */
    SDOM_EVENT_ON_INIT = 0x00000800,         /**< Initialization callback for objects; called after creation. */
    SDOM_EVENT_ON_QUIT,                      /**< Global callback fired during shutdown sequence. */
    SDOM_EVENT_ON_EVENT,                     /**< Generic hook for catching all events before normal dispatch. */
    SDOM_EVENT_ON_UPDATE,                    /**< Called once per frame before rendering; main update loop hook. */
    SDOM_EVENT_ON_RENDER,                    /**< Called each frame when object should perform its rendering. */
    SDOM_EVENT_ON_PRE_RENDER,                /**< Called before OnRender for pre-draw logic such as layout or transforms. */

    /* Frame -------------------------------------------------------------- */
    SDOM_EVENT_ENTER_FRAME = 0x00000900,     /**< Legacy per-frame tick event (use OnUpdate instead). */
    SDOM_EVENT_SDL_EVENT,                    /**< Raw SDL event wrapper; dispatched when unhandled by internal systems. */
    SDOM_EVENT_USER,                         /**< Reserved for custom or user-defined events created at runtime. */
    /**
     *  This last event is only for bounding internal arrays
     */
    SDOM_EVENT_LAST    = 0xFFFF,

    /* This just makes sure the enum is the size of Uint32 */
    SDOM_EVENT_ENUM_PADDING = 0x7FFFFFFF
} SDOM_EventType;

/** @} */

#ifdef __cplusplus
}
#endif
