/* Generated by SDOM DataRegistry */
#ifndef SDOM_CAPI_OBJECTS_H
#define SDOM_CAPI_OBJECTS_H

#ifdef __cplusplus
extern "C" {
#endif

/* Type: EventType::LeaveFullscreen */
typedef struct SDOM_EventType__LeaveFullscreen SDOM_EventType__LeaveFullscreen;

// property: captures
const char* SDOM_EventType__LeaveFullscreen_getcaptures(const SDOM_EventType__LeaveFullscreen*);
void SDOM_EventType__LeaveFullscreen_setcaptures(SDOM_EventType__LeaveFullscreen*, const char*);
// property: bubbles
const char* SDOM_EventType__LeaveFullscreen_getbubbles(const SDOM_EventType__LeaveFullscreen*);
void SDOM_EventType__LeaveFullscreen_setbubbles(SDOM_EventType__LeaveFullscreen*, const char*);
// property: target_only
const char* SDOM_EventType__LeaveFullscreen_gettarget_only(const SDOM_EventType__LeaveFullscreen*);
void SDOM_EventType__LeaveFullscreen_settarget_only(SDOM_EventType__LeaveFullscreen*, const char*);
// property: global
const char* SDOM_EventType__LeaveFullscreen_getglobal(const SDOM_EventType__LeaveFullscreen*);
void SDOM_EventType__LeaveFullscreen_setglobal(SDOM_EventType__LeaveFullscreen*, const char*);

/* Type: EventType::MouseMove */
typedef struct SDOM_EventType__MouseMove SDOM_EventType__MouseMove;

// property: captures
const char* SDOM_EventType__MouseMove_getcaptures(const SDOM_EventType__MouseMove*);
void SDOM_EventType__MouseMove_setcaptures(SDOM_EventType__MouseMove*, const char*);
// property: bubbles
const char* SDOM_EventType__MouseMove_getbubbles(const SDOM_EventType__MouseMove*);
void SDOM_EventType__MouseMove_setbubbles(SDOM_EventType__MouseMove*, const char*);
// property: target_only
const char* SDOM_EventType__MouseMove_gettarget_only(const SDOM_EventType__MouseMove*);
void SDOM_EventType__MouseMove_settarget_only(SDOM_EventType__MouseMove*, const char*);
// property: global
const char* SDOM_EventType__MouseMove_getglobal(const SDOM_EventType__MouseMove*);
void SDOM_EventType__MouseMove_setglobal(SDOM_EventType__MouseMove*, const char*);

/* Type: EventType::OnUpdate */
typedef struct SDOM_EventType__OnUpdate SDOM_EventType__OnUpdate;

// property: captures
const char* SDOM_EventType__OnUpdate_getcaptures(const SDOM_EventType__OnUpdate*);
void SDOM_EventType__OnUpdate_setcaptures(SDOM_EventType__OnUpdate*, const char*);
// property: bubbles
const char* SDOM_EventType__OnUpdate_getbubbles(const SDOM_EventType__OnUpdate*);
void SDOM_EventType__OnUpdate_setbubbles(SDOM_EventType__OnUpdate*, const char*);
// property: target_only
const char* SDOM_EventType__OnUpdate_gettarget_only(const SDOM_EventType__OnUpdate*);
void SDOM_EventType__OnUpdate_settarget_only(SDOM_EventType__OnUpdate*, const char*);
// property: global
const char* SDOM_EventType__OnUpdate_getglobal(const SDOM_EventType__OnUpdate*);
void SDOM_EventType__OnUpdate_setglobal(SDOM_EventType__OnUpdate*, const char*);

/* Type: EventType::KeyUp */
typedef struct SDOM_EventType__KeyUp SDOM_EventType__KeyUp;

// property: captures
const char* SDOM_EventType__KeyUp_getcaptures(const SDOM_EventType__KeyUp*);
void SDOM_EventType__KeyUp_setcaptures(SDOM_EventType__KeyUp*, const char*);
// property: bubbles
const char* SDOM_EventType__KeyUp_getbubbles(const SDOM_EventType__KeyUp*);
void SDOM_EventType__KeyUp_setbubbles(SDOM_EventType__KeyUp*, const char*);
// property: target_only
const char* SDOM_EventType__KeyUp_gettarget_only(const SDOM_EventType__KeyUp*);
void SDOM_EventType__KeyUp_settarget_only(SDOM_EventType__KeyUp*, const char*);
// property: global
const char* SDOM_EventType__KeyUp_getglobal(const SDOM_EventType__KeyUp*);
void SDOM_EventType__KeyUp_setglobal(SDOM_EventType__KeyUp*, const char*);

/* Type: EventType::OnRender */
typedef struct SDOM_EventType__OnRender SDOM_EventType__OnRender;

// property: captures
const char* SDOM_EventType__OnRender_getcaptures(const SDOM_EventType__OnRender*);
void SDOM_EventType__OnRender_setcaptures(SDOM_EventType__OnRender*, const char*);
// property: bubbles
const char* SDOM_EventType__OnRender_getbubbles(const SDOM_EventType__OnRender*);
void SDOM_EventType__OnRender_setbubbles(SDOM_EventType__OnRender*, const char*);
// property: target_only
const char* SDOM_EventType__OnRender_gettarget_only(const SDOM_EventType__OnRender*);
void SDOM_EventType__OnRender_settarget_only(SDOM_EventType__OnRender*, const char*);
// property: global
const char* SDOM_EventType__OnRender_getglobal(const SDOM_EventType__OnRender*);
void SDOM_EventType__OnRender_setglobal(SDOM_EventType__OnRender*, const char*);

/* Type: EventType::ValueChanged */
typedef struct SDOM_EventType__ValueChanged SDOM_EventType__ValueChanged;

// property: captures
const char* SDOM_EventType__ValueChanged_getcaptures(const SDOM_EventType__ValueChanged*);
void SDOM_EventType__ValueChanged_setcaptures(SDOM_EventType__ValueChanged*, const char*);
// property: bubbles
const char* SDOM_EventType__ValueChanged_getbubbles(const SDOM_EventType__ValueChanged*);
void SDOM_EventType__ValueChanged_setbubbles(SDOM_EventType__ValueChanged*, const char*);
// property: target_only
const char* SDOM_EventType__ValueChanged_gettarget_only(const SDOM_EventType__ValueChanged*);
void SDOM_EventType__ValueChanged_settarget_only(SDOM_EventType__ValueChanged*, const char*);
// property: global
const char* SDOM_EventType__ValueChanged_getglobal(const SDOM_EventType__ValueChanged*);
void SDOM_EventType__ValueChanged_setglobal(SDOM_EventType__ValueChanged*, const char*);

/* Type: EventType::MouseEnter */
typedef struct SDOM_EventType__MouseEnter SDOM_EventType__MouseEnter;

// property: captures
const char* SDOM_EventType__MouseEnter_getcaptures(const SDOM_EventType__MouseEnter*);
void SDOM_EventType__MouseEnter_setcaptures(SDOM_EventType__MouseEnter*, const char*);
// property: bubbles
const char* SDOM_EventType__MouseEnter_getbubbles(const SDOM_EventType__MouseEnter*);
void SDOM_EventType__MouseEnter_setbubbles(SDOM_EventType__MouseEnter*, const char*);
// property: target_only
const char* SDOM_EventType__MouseEnter_gettarget_only(const SDOM_EventType__MouseEnter*);
void SDOM_EventType__MouseEnter_settarget_only(SDOM_EventType__MouseEnter*, const char*);
// property: global
const char* SDOM_EventType__MouseEnter_getglobal(const SDOM_EventType__MouseEnter*);
void SDOM_EventType__MouseEnter_setglobal(SDOM_EventType__MouseEnter*, const char*);

/* Type: EventType::ClipboardPaste */
typedef struct SDOM_EventType__ClipboardPaste SDOM_EventType__ClipboardPaste;

// property: captures
const char* SDOM_EventType__ClipboardPaste_getcaptures(const SDOM_EventType__ClipboardPaste*);
void SDOM_EventType__ClipboardPaste_setcaptures(SDOM_EventType__ClipboardPaste*, const char*);
// property: bubbles
const char* SDOM_EventType__ClipboardPaste_getbubbles(const SDOM_EventType__ClipboardPaste*);
void SDOM_EventType__ClipboardPaste_setbubbles(SDOM_EventType__ClipboardPaste*, const char*);
// property: target_only
const char* SDOM_EventType__ClipboardPaste_gettarget_only(const SDOM_EventType__ClipboardPaste*);
void SDOM_EventType__ClipboardPaste_settarget_only(SDOM_EventType__ClipboardPaste*, const char*);
// property: global
const char* SDOM_EventType__ClipboardPaste_getglobal(const SDOM_EventType__ClipboardPaste*);
void SDOM_EventType__ClipboardPaste_setglobal(SDOM_EventType__ClipboardPaste*, const char*);

/* Type: EventType::StageOpened */
typedef struct SDOM_EventType__StageOpened SDOM_EventType__StageOpened;

// property: captures
const char* SDOM_EventType__StageOpened_getcaptures(const SDOM_EventType__StageOpened*);
void SDOM_EventType__StageOpened_setcaptures(SDOM_EventType__StageOpened*, const char*);
// property: bubbles
const char* SDOM_EventType__StageOpened_getbubbles(const SDOM_EventType__StageOpened*);
void SDOM_EventType__StageOpened_setbubbles(SDOM_EventType__StageOpened*, const char*);
// property: target_only
const char* SDOM_EventType__StageOpened_gettarget_only(const SDOM_EventType__StageOpened*);
void SDOM_EventType__StageOpened_settarget_only(SDOM_EventType__StageOpened*, const char*);
// property: global
const char* SDOM_EventType__StageOpened_getglobal(const SDOM_EventType__StageOpened*);
void SDOM_EventType__StageOpened_setglobal(SDOM_EventType__StageOpened*, const char*);

/* Type: EventType::MouseClick */
typedef struct SDOM_EventType__MouseClick SDOM_EventType__MouseClick;

// property: captures
const char* SDOM_EventType__MouseClick_getcaptures(const SDOM_EventType__MouseClick*);
void SDOM_EventType__MouseClick_setcaptures(SDOM_EventType__MouseClick*, const char*);
// property: bubbles
const char* SDOM_EventType__MouseClick_getbubbles(const SDOM_EventType__MouseClick*);
void SDOM_EventType__MouseClick_setbubbles(SDOM_EventType__MouseClick*, const char*);
// property: target_only
const char* SDOM_EventType__MouseClick_gettarget_only(const SDOM_EventType__MouseClick*);
void SDOM_EventType__MouseClick_settarget_only(SDOM_EventType__MouseClick*, const char*);
// property: global
const char* SDOM_EventType__MouseClick_getglobal(const SDOM_EventType__MouseClick*);
void SDOM_EventType__MouseClick_setglobal(SDOM_EventType__MouseClick*, const char*);

/* Type: EventType::SDL_Event */
typedef struct SDOM_EventType__SDL_Event SDOM_EventType__SDL_Event;

// property: captures
const char* SDOM_EventType__SDL_Event_getcaptures(const SDOM_EventType__SDL_Event*);
void SDOM_EventType__SDL_Event_setcaptures(SDOM_EventType__SDL_Event*, const char*);
// property: bubbles
const char* SDOM_EventType__SDL_Event_getbubbles(const SDOM_EventType__SDL_Event*);
void SDOM_EventType__SDL_Event_setbubbles(SDOM_EventType__SDL_Event*, const char*);
// property: target_only
const char* SDOM_EventType__SDL_Event_gettarget_only(const SDOM_EventType__SDL_Event*);
void SDOM_EventType__SDL_Event_settarget_only(SDOM_EventType__SDL_Event*, const char*);
// property: global
const char* SDOM_EventType__SDL_Event_getglobal(const SDOM_EventType__SDL_Event*);
void SDOM_EventType__SDL_Event_setglobal(SDOM_EventType__SDL_Event*, const char*);

/* Type: EventType::None */
typedef struct SDOM_EventType__None SDOM_EventType__None;

// property: captures
const char* SDOM_EventType__None_getcaptures(const SDOM_EventType__None*);
void SDOM_EventType__None_setcaptures(SDOM_EventType__None*, const char*);
// property: bubbles
const char* SDOM_EventType__None_getbubbles(const SDOM_EventType__None*);
void SDOM_EventType__None_setbubbles(SDOM_EventType__None*, const char*);
// property: target_only
const char* SDOM_EventType__None_gettarget_only(const SDOM_EventType__None*);
void SDOM_EventType__None_settarget_only(SDOM_EventType__None*, const char*);
// property: global
const char* SDOM_EventType__None_getglobal(const SDOM_EventType__None*);
void SDOM_EventType__None_setglobal(SDOM_EventType__None*, const char*);

/* Type: EventType::MouseButtonUp */
typedef struct SDOM_EventType__MouseButtonUp SDOM_EventType__MouseButtonUp;

// property: captures
const char* SDOM_EventType__MouseButtonUp_getcaptures(const SDOM_EventType__MouseButtonUp*);
void SDOM_EventType__MouseButtonUp_setcaptures(SDOM_EventType__MouseButtonUp*, const char*);
// property: bubbles
const char* SDOM_EventType__MouseButtonUp_getbubbles(const SDOM_EventType__MouseButtonUp*);
void SDOM_EventType__MouseButtonUp_setbubbles(SDOM_EventType__MouseButtonUp*, const char*);
// property: target_only
const char* SDOM_EventType__MouseButtonUp_gettarget_only(const SDOM_EventType__MouseButtonUp*);
void SDOM_EventType__MouseButtonUp_settarget_only(SDOM_EventType__MouseButtonUp*, const char*);
// property: global
const char* SDOM_EventType__MouseButtonUp_getglobal(const SDOM_EventType__MouseButtonUp*);
void SDOM_EventType__MouseButtonUp_setglobal(SDOM_EventType__MouseButtonUp*, const char*);

/* Type: EventType::Hidden */
typedef struct SDOM_EventType__Hidden SDOM_EventType__Hidden;

// property: captures
const char* SDOM_EventType__Hidden_getcaptures(const SDOM_EventType__Hidden*);
void SDOM_EventType__Hidden_setcaptures(SDOM_EventType__Hidden*, const char*);
// property: bubbles
const char* SDOM_EventType__Hidden_getbubbles(const SDOM_EventType__Hidden*);
void SDOM_EventType__Hidden_setbubbles(SDOM_EventType__Hidden*, const char*);
// property: target_only
const char* SDOM_EventType__Hidden_gettarget_only(const SDOM_EventType__Hidden*);
void SDOM_EventType__Hidden_settarget_only(SDOM_EventType__Hidden*, const char*);
// property: global
const char* SDOM_EventType__Hidden_getglobal(const SDOM_EventType__Hidden*);
void SDOM_EventType__Hidden_setglobal(SDOM_EventType__Hidden*, const char*);

/* Type: EventType::Dragging */
typedef struct SDOM_EventType__Dragging SDOM_EventType__Dragging;

// property: captures
const char* SDOM_EventType__Dragging_getcaptures(const SDOM_EventType__Dragging*);
void SDOM_EventType__Dragging_setcaptures(SDOM_EventType__Dragging*, const char*);
// property: bubbles
const char* SDOM_EventType__Dragging_getbubbles(const SDOM_EventType__Dragging*);
void SDOM_EventType__Dragging_setbubbles(SDOM_EventType__Dragging*, const char*);
// property: target_only
const char* SDOM_EventType__Dragging_gettarget_only(const SDOM_EventType__Dragging*);
void SDOM_EventType__Dragging_settarget_only(SDOM_EventType__Dragging*, const char*);
// property: global
const char* SDOM_EventType__Dragging_getglobal(const SDOM_EventType__Dragging*);
void SDOM_EventType__Dragging_setglobal(SDOM_EventType__Dragging*, const char*);

/* Type: EventType::TimerComplete */
typedef struct SDOM_EventType__TimerComplete SDOM_EventType__TimerComplete;

// property: captures
const char* SDOM_EventType__TimerComplete_getcaptures(const SDOM_EventType__TimerComplete*);
void SDOM_EventType__TimerComplete_setcaptures(SDOM_EventType__TimerComplete*, const char*);
// property: bubbles
const char* SDOM_EventType__TimerComplete_getbubbles(const SDOM_EventType__TimerComplete*);
void SDOM_EventType__TimerComplete_setbubbles(SDOM_EventType__TimerComplete*, const char*);
// property: target_only
const char* SDOM_EventType__TimerComplete_gettarget_only(const SDOM_EventType__TimerComplete*);
void SDOM_EventType__TimerComplete_settarget_only(SDOM_EventType__TimerComplete*, const char*);
// property: global
const char* SDOM_EventType__TimerComplete_getglobal(const SDOM_EventType__TimerComplete*);
void SDOM_EventType__TimerComplete_setglobal(SDOM_EventType__TimerComplete*, const char*);

/* Type: EventType::TimerStop */
typedef struct SDOM_EventType__TimerStop SDOM_EventType__TimerStop;

// property: captures
const char* SDOM_EventType__TimerStop_getcaptures(const SDOM_EventType__TimerStop*);
void SDOM_EventType__TimerStop_setcaptures(SDOM_EventType__TimerStop*, const char*);
// property: bubbles
const char* SDOM_EventType__TimerStop_getbubbles(const SDOM_EventType__TimerStop*);
void SDOM_EventType__TimerStop_setbubbles(SDOM_EventType__TimerStop*, const char*);
// property: target_only
const char* SDOM_EventType__TimerStop_gettarget_only(const SDOM_EventType__TimerStop*);
void SDOM_EventType__TimerStop_settarget_only(SDOM_EventType__TimerStop*, const char*);
// property: global
const char* SDOM_EventType__TimerStop_getglobal(const SDOM_EventType__TimerStop*);
void SDOM_EventType__TimerStop_setglobal(SDOM_EventType__TimerStop*, const char*);

/* Type: EventType::Hide */
typedef struct SDOM_EventType__Hide SDOM_EventType__Hide;

// property: captures
const char* SDOM_EventType__Hide_getcaptures(const SDOM_EventType__Hide*);
void SDOM_EventType__Hide_setcaptures(SDOM_EventType__Hide*, const char*);
// property: bubbles
const char* SDOM_EventType__Hide_getbubbles(const SDOM_EventType__Hide*);
void SDOM_EventType__Hide_setbubbles(SDOM_EventType__Hide*, const char*);
// property: target_only
const char* SDOM_EventType__Hide_gettarget_only(const SDOM_EventType__Hide*);
void SDOM_EventType__Hide_settarget_only(SDOM_EventType__Hide*, const char*);
// property: global
const char* SDOM_EventType__Hide_getglobal(const SDOM_EventType__Hide*);
void SDOM_EventType__Hide_setglobal(SDOM_EventType__Hide*, const char*);

/* Type: EventType::TimerStart */
typedef struct SDOM_EventType__TimerStart SDOM_EventType__TimerStart;

// property: captures
const char* SDOM_EventType__TimerStart_getcaptures(const SDOM_EventType__TimerStart*);
void SDOM_EventType__TimerStart_setcaptures(SDOM_EventType__TimerStart*, const char*);
// property: bubbles
const char* SDOM_EventType__TimerStart_getbubbles(const SDOM_EventType__TimerStart*);
void SDOM_EventType__TimerStart_setbubbles(SDOM_EventType__TimerStart*, const char*);
// property: target_only
const char* SDOM_EventType__TimerStart_gettarget_only(const SDOM_EventType__TimerStart*);
void SDOM_EventType__TimerStart_settarget_only(SDOM_EventType__TimerStart*, const char*);
// property: global
const char* SDOM_EventType__TimerStart_getglobal(const SDOM_EventType__TimerStart*);
void SDOM_EventType__TimerStart_setglobal(SDOM_EventType__TimerStart*, const char*);

/* Type: EventType::TimerPause */
typedef struct SDOM_EventType__TimerPause SDOM_EventType__TimerPause;

// property: captures
const char* SDOM_EventType__TimerPause_getcaptures(const SDOM_EventType__TimerPause*);
void SDOM_EventType__TimerPause_setcaptures(SDOM_EventType__TimerPause*, const char*);
// property: bubbles
const char* SDOM_EventType__TimerPause_getbubbles(const SDOM_EventType__TimerPause*);
void SDOM_EventType__TimerPause_setbubbles(SDOM_EventType__TimerPause*, const char*);
// property: target_only
const char* SDOM_EventType__TimerPause_gettarget_only(const SDOM_EventType__TimerPause*);
void SDOM_EventType__TimerPause_settarget_only(SDOM_EventType__TimerPause*, const char*);
// property: global
const char* SDOM_EventType__TimerPause_getglobal(const SDOM_EventType__TimerPause*);
void SDOM_EventType__TimerPause_setglobal(SDOM_EventType__TimerPause*, const char*);

/* Type: EventType::TimerCycleComplete */
typedef struct SDOM_EventType__TimerCycleComplete SDOM_EventType__TimerCycleComplete;

// property: captures
const char* SDOM_EventType__TimerCycleComplete_getcaptures(const SDOM_EventType__TimerCycleComplete*);
void SDOM_EventType__TimerCycleComplete_setcaptures(SDOM_EventType__TimerCycleComplete*, const char*);
// property: bubbles
const char* SDOM_EventType__TimerCycleComplete_getbubbles(const SDOM_EventType__TimerCycleComplete*);
void SDOM_EventType__TimerCycleComplete_setbubbles(SDOM_EventType__TimerCycleComplete*, const char*);
// property: target_only
const char* SDOM_EventType__TimerCycleComplete_gettarget_only(const SDOM_EventType__TimerCycleComplete*);
void SDOM_EventType__TimerCycleComplete_settarget_only(SDOM_EventType__TimerCycleComplete*, const char*);
// property: global
const char* SDOM_EventType__TimerCycleComplete_getglobal(const SDOM_EventType__TimerCycleComplete*);
void SDOM_EventType__TimerCycleComplete_setglobal(SDOM_EventType__TimerCycleComplete*, const char*);

/* Type: EventType::RemovedFromStage */
typedef struct SDOM_EventType__RemovedFromStage SDOM_EventType__RemovedFromStage;

// property: captures
const char* SDOM_EventType__RemovedFromStage_getcaptures(const SDOM_EventType__RemovedFromStage*);
void SDOM_EventType__RemovedFromStage_setcaptures(SDOM_EventType__RemovedFromStage*, const char*);
// property: bubbles
const char* SDOM_EventType__RemovedFromStage_getbubbles(const SDOM_EventType__RemovedFromStage*);
void SDOM_EventType__RemovedFromStage_setbubbles(SDOM_EventType__RemovedFromStage*, const char*);
// property: target_only
const char* SDOM_EventType__RemovedFromStage_gettarget_only(const SDOM_EventType__RemovedFromStage*);
void SDOM_EventType__RemovedFromStage_settarget_only(SDOM_EventType__RemovedFromStage*, const char*);
// property: global
const char* SDOM_EventType__RemovedFromStage_getglobal(const SDOM_EventType__RemovedFromStage*);
void SDOM_EventType__RemovedFromStage_setglobal(SDOM_EventType__RemovedFromStage*, const char*);

/* Type: EventType::Drop */
typedef struct SDOM_EventType__Drop SDOM_EventType__Drop;

// property: captures
const char* SDOM_EventType__Drop_getcaptures(const SDOM_EventType__Drop*);
void SDOM_EventType__Drop_setcaptures(SDOM_EventType__Drop*, const char*);
// property: bubbles
const char* SDOM_EventType__Drop_getbubbles(const SDOM_EventType__Drop*);
void SDOM_EventType__Drop_setbubbles(SDOM_EventType__Drop*, const char*);
// property: target_only
const char* SDOM_EventType__Drop_gettarget_only(const SDOM_EventType__Drop*);
void SDOM_EventType__Drop_settarget_only(SDOM_EventType__Drop*, const char*);
// property: global
const char* SDOM_EventType__Drop_getglobal(const SDOM_EventType__Drop*);
void SDOM_EventType__Drop_setglobal(SDOM_EventType__Drop*, const char*);

/* Type: EventType::OnQuit */
typedef struct SDOM_EventType__OnQuit SDOM_EventType__OnQuit;

// property: captures
const char* SDOM_EventType__OnQuit_getcaptures(const SDOM_EventType__OnQuit*);
void SDOM_EventType__OnQuit_setcaptures(SDOM_EventType__OnQuit*, const char*);
// property: bubbles
const char* SDOM_EventType__OnQuit_getbubbles(const SDOM_EventType__OnQuit*);
void SDOM_EventType__OnQuit_setbubbles(SDOM_EventType__OnQuit*, const char*);
// property: target_only
const char* SDOM_EventType__OnQuit_gettarget_only(const SDOM_EventType__OnQuit*);
void SDOM_EventType__OnQuit_settarget_only(SDOM_EventType__OnQuit*, const char*);
// property: global
const char* SDOM_EventType__OnQuit_getglobal(const SDOM_EventType__OnQuit*);
void SDOM_EventType__OnQuit_setglobal(SDOM_EventType__OnQuit*, const char*);

/* Type: EventType::ClipboardCopy */
typedef struct SDOM_EventType__ClipboardCopy SDOM_EventType__ClipboardCopy;

// property: captures
const char* SDOM_EventType__ClipboardCopy_getcaptures(const SDOM_EventType__ClipboardCopy*);
void SDOM_EventType__ClipboardCopy_setcaptures(SDOM_EventType__ClipboardCopy*, const char*);
// property: bubbles
const char* SDOM_EventType__ClipboardCopy_getbubbles(const SDOM_EventType__ClipboardCopy*);
void SDOM_EventType__ClipboardCopy_setbubbles(SDOM_EventType__ClipboardCopy*, const char*);
// property: target_only
const char* SDOM_EventType__ClipboardCopy_gettarget_only(const SDOM_EventType__ClipboardCopy*);
void SDOM_EventType__ClipboardCopy_settarget_only(SDOM_EventType__ClipboardCopy*, const char*);
// property: global
const char* SDOM_EventType__ClipboardCopy_getglobal(const SDOM_EventType__ClipboardCopy*);
void SDOM_EventType__ClipboardCopy_setglobal(SDOM_EventType__ClipboardCopy*, const char*);

/* Type: EventType::Added */
typedef struct SDOM_EventType__Added SDOM_EventType__Added;

// property: captures
const char* SDOM_EventType__Added_getcaptures(const SDOM_EventType__Added*);
void SDOM_EventType__Added_setcaptures(SDOM_EventType__Added*, const char*);
// property: bubbles
const char* SDOM_EventType__Added_getbubbles(const SDOM_EventType__Added*);
void SDOM_EventType__Added_setbubbles(SDOM_EventType__Added*, const char*);
// property: target_only
const char* SDOM_EventType__Added_gettarget_only(const SDOM_EventType__Added*);
void SDOM_EventType__Added_settarget_only(SDOM_EventType__Added*, const char*);
// property: global
const char* SDOM_EventType__Added_getglobal(const SDOM_EventType__Added*);
void SDOM_EventType__Added_setglobal(SDOM_EventType__Added*, const char*);

/* Type: EventType::MouseButtonDown */
typedef struct SDOM_EventType__MouseButtonDown SDOM_EventType__MouseButtonDown;

// property: captures
const char* SDOM_EventType__MouseButtonDown_getcaptures(const SDOM_EventType__MouseButtonDown*);
void SDOM_EventType__MouseButtonDown_setcaptures(SDOM_EventType__MouseButtonDown*, const char*);
// property: bubbles
const char* SDOM_EventType__MouseButtonDown_getbubbles(const SDOM_EventType__MouseButtonDown*);
void SDOM_EventType__MouseButtonDown_setbubbles(SDOM_EventType__MouseButtonDown*, const char*);
// property: target_only
const char* SDOM_EventType__MouseButtonDown_gettarget_only(const SDOM_EventType__MouseButtonDown*);
void SDOM_EventType__MouseButtonDown_settarget_only(SDOM_EventType__MouseButtonDown*, const char*);
// property: global
const char* SDOM_EventType__MouseButtonDown_getglobal(const SDOM_EventType__MouseButtonDown*);
void SDOM_EventType__MouseButtonDown_setglobal(SDOM_EventType__MouseButtonDown*, const char*);

/* Type: EventType::FocusGained */
typedef struct SDOM_EventType__FocusGained SDOM_EventType__FocusGained;

// property: captures
const char* SDOM_EventType__FocusGained_getcaptures(const SDOM_EventType__FocusGained*);
void SDOM_EventType__FocusGained_setcaptures(SDOM_EventType__FocusGained*, const char*);
// property: bubbles
const char* SDOM_EventType__FocusGained_getbubbles(const SDOM_EventType__FocusGained*);
void SDOM_EventType__FocusGained_setbubbles(SDOM_EventType__FocusGained*, const char*);
// property: target_only
const char* SDOM_EventType__FocusGained_gettarget_only(const SDOM_EventType__FocusGained*);
void SDOM_EventType__FocusGained_settarget_only(SDOM_EventType__FocusGained*, const char*);
// property: global
const char* SDOM_EventType__FocusGained_getglobal(const SDOM_EventType__FocusGained*);
void SDOM_EventType__FocusGained_setglobal(SDOM_EventType__FocusGained*, const char*);

/* Type: EventType::OnPreRender */
typedef struct SDOM_EventType__OnPreRender SDOM_EventType__OnPreRender;

// property: captures
const char* SDOM_EventType__OnPreRender_getcaptures(const SDOM_EventType__OnPreRender*);
void SDOM_EventType__OnPreRender_setcaptures(SDOM_EventType__OnPreRender*, const char*);
// property: bubbles
const char* SDOM_EventType__OnPreRender_getbubbles(const SDOM_EventType__OnPreRender*);
void SDOM_EventType__OnPreRender_setbubbles(SDOM_EventType__OnPreRender*, const char*);
// property: target_only
const char* SDOM_EventType__OnPreRender_gettarget_only(const SDOM_EventType__OnPreRender*);
void SDOM_EventType__OnPreRender_settarget_only(SDOM_EventType__OnPreRender*, const char*);
// property: global
const char* SDOM_EventType__OnPreRender_getglobal(const SDOM_EventType__OnPreRender*);
void SDOM_EventType__OnPreRender_setglobal(SDOM_EventType__OnPreRender*, const char*);

/* Type: EventType::TimerTick */
typedef struct SDOM_EventType__TimerTick SDOM_EventType__TimerTick;

// property: captures
const char* SDOM_EventType__TimerTick_getcaptures(const SDOM_EventType__TimerTick*);
void SDOM_EventType__TimerTick_setcaptures(SDOM_EventType__TimerTick*, const char*);
// property: bubbles
const char* SDOM_EventType__TimerTick_getbubbles(const SDOM_EventType__TimerTick*);
void SDOM_EventType__TimerTick_setbubbles(SDOM_EventType__TimerTick*, const char*);
// property: target_only
const char* SDOM_EventType__TimerTick_gettarget_only(const SDOM_EventType__TimerTick*);
void SDOM_EventType__TimerTick_settarget_only(SDOM_EventType__TimerTick*, const char*);
// property: global
const char* SDOM_EventType__TimerTick_getglobal(const SDOM_EventType__TimerTick*);
void SDOM_EventType__TimerTick_setglobal(SDOM_EventType__TimerTick*, const char*);

/* Type: EventType::KeyDown */
typedef struct SDOM_EventType__KeyDown SDOM_EventType__KeyDown;

// property: captures
const char* SDOM_EventType__KeyDown_getcaptures(const SDOM_EventType__KeyDown*);
void SDOM_EventType__KeyDown_setcaptures(SDOM_EventType__KeyDown*, const char*);
// property: bubbles
const char* SDOM_EventType__KeyDown_getbubbles(const SDOM_EventType__KeyDown*);
void SDOM_EventType__KeyDown_setbubbles(SDOM_EventType__KeyDown*, const char*);
// property: target_only
const char* SDOM_EventType__KeyDown_gettarget_only(const SDOM_EventType__KeyDown*);
void SDOM_EventType__KeyDown_settarget_only(SDOM_EventType__KeyDown*, const char*);
// property: global
const char* SDOM_EventType__KeyDown_getglobal(const SDOM_EventType__KeyDown*);
void SDOM_EventType__KeyDown_setglobal(SDOM_EventType__KeyDown*, const char*);

/* Type: EventType::OnEvent */
typedef struct SDOM_EventType__OnEvent SDOM_EventType__OnEvent;

// property: captures
const char* SDOM_EventType__OnEvent_getcaptures(const SDOM_EventType__OnEvent*);
void SDOM_EventType__OnEvent_setcaptures(SDOM_EventType__OnEvent*, const char*);
// property: bubbles
const char* SDOM_EventType__OnEvent_getbubbles(const SDOM_EventType__OnEvent*);
void SDOM_EventType__OnEvent_setbubbles(SDOM_EventType__OnEvent*, const char*);
// property: target_only
const char* SDOM_EventType__OnEvent_gettarget_only(const SDOM_EventType__OnEvent*);
void SDOM_EventType__OnEvent_settarget_only(SDOM_EventType__OnEvent*, const char*);
// property: global
const char* SDOM_EventType__OnEvent_getglobal(const SDOM_EventType__OnEvent*);
void SDOM_EventType__OnEvent_setglobal(SDOM_EventType__OnEvent*, const char*);

/* Type: EventType::StageClosed */
typedef struct SDOM_EventType__StageClosed SDOM_EventType__StageClosed;

// property: captures
const char* SDOM_EventType__StageClosed_getcaptures(const SDOM_EventType__StageClosed*);
void SDOM_EventType__StageClosed_setcaptures(SDOM_EventType__StageClosed*, const char*);
// property: bubbles
const char* SDOM_EventType__StageClosed_getbubbles(const SDOM_EventType__StageClosed*);
void SDOM_EventType__StageClosed_setbubbles(SDOM_EventType__StageClosed*, const char*);
// property: target_only
const char* SDOM_EventType__StageClosed_gettarget_only(const SDOM_EventType__StageClosed*);
void SDOM_EventType__StageClosed_settarget_only(SDOM_EventType__StageClosed*, const char*);
// property: global
const char* SDOM_EventType__StageClosed_getglobal(const SDOM_EventType__StageClosed*);
void SDOM_EventType__StageClosed_setglobal(SDOM_EventType__StageClosed*, const char*);

/* Type: EventType::Disabled */
typedef struct SDOM_EventType__Disabled SDOM_EventType__Disabled;

// property: captures
const char* SDOM_EventType__Disabled_getcaptures(const SDOM_EventType__Disabled*);
void SDOM_EventType__Disabled_setcaptures(SDOM_EventType__Disabled*, const char*);
// property: bubbles
const char* SDOM_EventType__Disabled_getbubbles(const SDOM_EventType__Disabled*);
void SDOM_EventType__Disabled_setbubbles(SDOM_EventType__Disabled*, const char*);
// property: target_only
const char* SDOM_EventType__Disabled_gettarget_only(const SDOM_EventType__Disabled*);
void SDOM_EventType__Disabled_settarget_only(SDOM_EventType__Disabled*, const char*);
// property: global
const char* SDOM_EventType__Disabled_getglobal(const SDOM_EventType__Disabled*);
void SDOM_EventType__Disabled_setglobal(SDOM_EventType__Disabled*, const char*);

/* Type: EventType::EnterFrame */
typedef struct SDOM_EventType__EnterFrame SDOM_EventType__EnterFrame;

// property: captures
const char* SDOM_EventType__EnterFrame_getcaptures(const SDOM_EventType__EnterFrame*);
void SDOM_EventType__EnterFrame_setcaptures(SDOM_EventType__EnterFrame*, const char*);
// property: bubbles
const char* SDOM_EventType__EnterFrame_getbubbles(const SDOM_EventType__EnterFrame*);
void SDOM_EventType__EnterFrame_setbubbles(SDOM_EventType__EnterFrame*, const char*);
// property: target_only
const char* SDOM_EventType__EnterFrame_gettarget_only(const SDOM_EventType__EnterFrame*);
void SDOM_EventType__EnterFrame_settarget_only(SDOM_EventType__EnterFrame*, const char*);
// property: global
const char* SDOM_EventType__EnterFrame_getglobal(const SDOM_EventType__EnterFrame*);
void SDOM_EventType__EnterFrame_setglobal(SDOM_EventType__EnterFrame*, const char*);

/* Type: EventType::AddedToStage */
typedef struct SDOM_EventType__AddedToStage SDOM_EventType__AddedToStage;

// property: captures
const char* SDOM_EventType__AddedToStage_getcaptures(const SDOM_EventType__AddedToStage*);
void SDOM_EventType__AddedToStage_setcaptures(SDOM_EventType__AddedToStage*, const char*);
// property: bubbles
const char* SDOM_EventType__AddedToStage_getbubbles(const SDOM_EventType__AddedToStage*);
void SDOM_EventType__AddedToStage_setbubbles(SDOM_EventType__AddedToStage*, const char*);
// property: target_only
const char* SDOM_EventType__AddedToStage_gettarget_only(const SDOM_EventType__AddedToStage*);
void SDOM_EventType__AddedToStage_settarget_only(SDOM_EventType__AddedToStage*, const char*);
// property: global
const char* SDOM_EventType__AddedToStage_getglobal(const SDOM_EventType__AddedToStage*);
void SDOM_EventType__AddedToStage_setglobal(SDOM_EventType__AddedToStage*, const char*);

/* Type: EventType::MouseDoubleClick */
typedef struct SDOM_EventType__MouseDoubleClick SDOM_EventType__MouseDoubleClick;

// property: captures
const char* SDOM_EventType__MouseDoubleClick_getcaptures(const SDOM_EventType__MouseDoubleClick*);
void SDOM_EventType__MouseDoubleClick_setcaptures(SDOM_EventType__MouseDoubleClick*, const char*);
// property: bubbles
const char* SDOM_EventType__MouseDoubleClick_getbubbles(const SDOM_EventType__MouseDoubleClick*);
void SDOM_EventType__MouseDoubleClick_setbubbles(SDOM_EventType__MouseDoubleClick*, const char*);
// property: target_only
const char* SDOM_EventType__MouseDoubleClick_gettarget_only(const SDOM_EventType__MouseDoubleClick*);
void SDOM_EventType__MouseDoubleClick_settarget_only(SDOM_EventType__MouseDoubleClick*, const char*);
// property: global
const char* SDOM_EventType__MouseDoubleClick_getglobal(const SDOM_EventType__MouseDoubleClick*);
void SDOM_EventType__MouseDoubleClick_setglobal(SDOM_EventType__MouseDoubleClick*, const char*);

/* Type: EventType::StateChanged */
typedef struct SDOM_EventType__StateChanged SDOM_EventType__StateChanged;

// property: captures
const char* SDOM_EventType__StateChanged_getcaptures(const SDOM_EventType__StateChanged*);
void SDOM_EventType__StateChanged_setcaptures(SDOM_EventType__StateChanged*, const char*);
// property: bubbles
const char* SDOM_EventType__StateChanged_getbubbles(const SDOM_EventType__StateChanged*);
void SDOM_EventType__StateChanged_setbubbles(SDOM_EventType__StateChanged*, const char*);
// property: target_only
const char* SDOM_EventType__StateChanged_gettarget_only(const SDOM_EventType__StateChanged*);
void SDOM_EventType__StateChanged_settarget_only(SDOM_EventType__StateChanged*, const char*);
// property: global
const char* SDOM_EventType__StateChanged_getglobal(const SDOM_EventType__StateChanged*);
void SDOM_EventType__StateChanged_setglobal(SDOM_EventType__StateChanged*, const char*);

/* Type: EventType::Removed */
typedef struct SDOM_EventType__Removed SDOM_EventType__Removed;

// property: captures
const char* SDOM_EventType__Removed_getcaptures(const SDOM_EventType__Removed*);
void SDOM_EventType__Removed_setcaptures(SDOM_EventType__Removed*, const char*);
// property: bubbles
const char* SDOM_EventType__Removed_getbubbles(const SDOM_EventType__Removed*);
void SDOM_EventType__Removed_setbubbles(SDOM_EventType__Removed*, const char*);
// property: target_only
const char* SDOM_EventType__Removed_gettarget_only(const SDOM_EventType__Removed*);
void SDOM_EventType__Removed_settarget_only(SDOM_EventType__Removed*, const char*);
// property: global
const char* SDOM_EventType__Removed_getglobal(const SDOM_EventType__Removed*);
void SDOM_EventType__Removed_setglobal(SDOM_EventType__Removed*, const char*);

/* Type: EventType::OnInit */
typedef struct SDOM_EventType__OnInit SDOM_EventType__OnInit;

// property: captures
const char* SDOM_EventType__OnInit_getcaptures(const SDOM_EventType__OnInit*);
void SDOM_EventType__OnInit_setcaptures(SDOM_EventType__OnInit*, const char*);
// property: bubbles
const char* SDOM_EventType__OnInit_getbubbles(const SDOM_EventType__OnInit*);
void SDOM_EventType__OnInit_setbubbles(SDOM_EventType__OnInit*, const char*);
// property: target_only
const char* SDOM_EventType__OnInit_gettarget_only(const SDOM_EventType__OnInit*);
void SDOM_EventType__OnInit_settarget_only(SDOM_EventType__OnInit*, const char*);
// property: global
const char* SDOM_EventType__OnInit_getglobal(const SDOM_EventType__OnInit*);
void SDOM_EventType__OnInit_setglobal(SDOM_EventType__OnInit*, const char*);

/* Type: EventType::User */
typedef struct SDOM_EventType__User SDOM_EventType__User;

// property: captures
const char* SDOM_EventType__User_getcaptures(const SDOM_EventType__User*);
void SDOM_EventType__User_setcaptures(SDOM_EventType__User*, const char*);
// property: bubbles
const char* SDOM_EventType__User_getbubbles(const SDOM_EventType__User*);
void SDOM_EventType__User_setbubbles(SDOM_EventType__User*, const char*);
// property: target_only
const char* SDOM_EventType__User_gettarget_only(const SDOM_EventType__User*);
void SDOM_EventType__User_settarget_only(SDOM_EventType__User*, const char*);
// property: global
const char* SDOM_EventType__User_getglobal(const SDOM_EventType__User*);
void SDOM_EventType__User_setglobal(SDOM_EventType__User*, const char*);

/* Type: EventType::SelectionChanged */
typedef struct SDOM_EventType__SelectionChanged SDOM_EventType__SelectionChanged;

// property: captures
const char* SDOM_EventType__SelectionChanged_getcaptures(const SDOM_EventType__SelectionChanged*);
void SDOM_EventType__SelectionChanged_setcaptures(SDOM_EventType__SelectionChanged*, const char*);
// property: bubbles
const char* SDOM_EventType__SelectionChanged_getbubbles(const SDOM_EventType__SelectionChanged*);
void SDOM_EventType__SelectionChanged_setbubbles(SDOM_EventType__SelectionChanged*, const char*);
// property: target_only
const char* SDOM_EventType__SelectionChanged_gettarget_only(const SDOM_EventType__SelectionChanged*);
void SDOM_EventType__SelectionChanged_settarget_only(SDOM_EventType__SelectionChanged*, const char*);
// property: global
const char* SDOM_EventType__SelectionChanged_getglobal(const SDOM_EventType__SelectionChanged*);
void SDOM_EventType__SelectionChanged_setglobal(SDOM_EventType__SelectionChanged*, const char*);

/* Type: EventType::Drag */
typedef struct SDOM_EventType__Drag SDOM_EventType__Drag;

// property: captures
const char* SDOM_EventType__Drag_getcaptures(const SDOM_EventType__Drag*);
void SDOM_EventType__Drag_setcaptures(SDOM_EventType__Drag*, const char*);
// property: bubbles
const char* SDOM_EventType__Drag_getbubbles(const SDOM_EventType__Drag*);
void SDOM_EventType__Drag_setbubbles(SDOM_EventType__Drag*, const char*);
// property: target_only
const char* SDOM_EventType__Drag_gettarget_only(const SDOM_EventType__Drag*);
void SDOM_EventType__Drag_settarget_only(SDOM_EventType__Drag*, const char*);
// property: global
const char* SDOM_EventType__Drag_getglobal(const SDOM_EventType__Drag*);
void SDOM_EventType__Drag_setglobal(SDOM_EventType__Drag*, const char*);

/* Type: EventType::Move */
typedef struct SDOM_EventType__Move SDOM_EventType__Move;

// property: captures
const char* SDOM_EventType__Move_getcaptures(const SDOM_EventType__Move*);
void SDOM_EventType__Move_setcaptures(SDOM_EventType__Move*, const char*);
// property: bubbles
const char* SDOM_EventType__Move_getbubbles(const SDOM_EventType__Move*);
void SDOM_EventType__Move_setbubbles(SDOM_EventType__Move*, const char*);
// property: target_only
const char* SDOM_EventType__Move_gettarget_only(const SDOM_EventType__Move*);
void SDOM_EventType__Move_settarget_only(SDOM_EventType__Move*, const char*);
// property: global
const char* SDOM_EventType__Move_getglobal(const SDOM_EventType__Move*);
void SDOM_EventType__Move_setglobal(SDOM_EventType__Move*, const char*);

/* Type: EventType::MouseLeave */
typedef struct SDOM_EventType__MouseLeave SDOM_EventType__MouseLeave;

// property: captures
const char* SDOM_EventType__MouseLeave_getcaptures(const SDOM_EventType__MouseLeave*);
void SDOM_EventType__MouseLeave_setcaptures(SDOM_EventType__MouseLeave*, const char*);
// property: bubbles
const char* SDOM_EventType__MouseLeave_getbubbles(const SDOM_EventType__MouseLeave*);
void SDOM_EventType__MouseLeave_setbubbles(SDOM_EventType__MouseLeave*, const char*);
// property: target_only
const char* SDOM_EventType__MouseLeave_gettarget_only(const SDOM_EventType__MouseLeave*);
void SDOM_EventType__MouseLeave_settarget_only(SDOM_EventType__MouseLeave*, const char*);
// property: global
const char* SDOM_EventType__MouseLeave_getglobal(const SDOM_EventType__MouseLeave*);
void SDOM_EventType__MouseLeave_setglobal(SDOM_EventType__MouseLeave*, const char*);

/* Type: EventType::Resize */
typedef struct SDOM_EventType__Resize SDOM_EventType__Resize;

// property: captures
const char* SDOM_EventType__Resize_getcaptures(const SDOM_EventType__Resize*);
void SDOM_EventType__Resize_setcaptures(SDOM_EventType__Resize*, const char*);
// property: bubbles
const char* SDOM_EventType__Resize_getbubbles(const SDOM_EventType__Resize*);
void SDOM_EventType__Resize_setbubbles(SDOM_EventType__Resize*, const char*);
// property: target_only
const char* SDOM_EventType__Resize_gettarget_only(const SDOM_EventType__Resize*);
void SDOM_EventType__Resize_settarget_only(SDOM_EventType__Resize*, const char*);
// property: global
const char* SDOM_EventType__Resize_getglobal(const SDOM_EventType__Resize*);
void SDOM_EventType__Resize_setglobal(SDOM_EventType__Resize*, const char*);

/* Type: EventType::TextInput */
typedef struct SDOM_EventType__TextInput SDOM_EventType__TextInput;

// property: captures
const char* SDOM_EventType__TextInput_getcaptures(const SDOM_EventType__TextInput*);
void SDOM_EventType__TextInput_setcaptures(SDOM_EventType__TextInput*, const char*);
// property: bubbles
const char* SDOM_EventType__TextInput_getbubbles(const SDOM_EventType__TextInput*);
void SDOM_EventType__TextInput_setbubbles(SDOM_EventType__TextInput*, const char*);
// property: target_only
const char* SDOM_EventType__TextInput_gettarget_only(const SDOM_EventType__TextInput*);
void SDOM_EventType__TextInput_settarget_only(SDOM_EventType__TextInput*, const char*);
// property: global
const char* SDOM_EventType__TextInput_getglobal(const SDOM_EventType__TextInput*);
void SDOM_EventType__TextInput_setglobal(SDOM_EventType__TextInput*, const char*);

/* Type: EventType::Visible */
typedef struct SDOM_EventType__Visible SDOM_EventType__Visible;

// property: captures
const char* SDOM_EventType__Visible_getcaptures(const SDOM_EventType__Visible*);
void SDOM_EventType__Visible_setcaptures(SDOM_EventType__Visible*, const char*);
// property: bubbles
const char* SDOM_EventType__Visible_getbubbles(const SDOM_EventType__Visible*);
void SDOM_EventType__Visible_setbubbles(SDOM_EventType__Visible*, const char*);
// property: target_only
const char* SDOM_EventType__Visible_gettarget_only(const SDOM_EventType__Visible*);
void SDOM_EventType__Visible_settarget_only(SDOM_EventType__Visible*, const char*);
// property: global
const char* SDOM_EventType__Visible_getglobal(const SDOM_EventType__Visible*);
void SDOM_EventType__Visible_setglobal(SDOM_EventType__Visible*, const char*);

/* Type: EventType::FocusLost */
typedef struct SDOM_EventType__FocusLost SDOM_EventType__FocusLost;

// property: captures
const char* SDOM_EventType__FocusLost_getcaptures(const SDOM_EventType__FocusLost*);
void SDOM_EventType__FocusLost_setcaptures(SDOM_EventType__FocusLost*, const char*);
// property: bubbles
const char* SDOM_EventType__FocusLost_getbubbles(const SDOM_EventType__FocusLost*);
void SDOM_EventType__FocusLost_setbubbles(SDOM_EventType__FocusLost*, const char*);
// property: target_only
const char* SDOM_EventType__FocusLost_gettarget_only(const SDOM_EventType__FocusLost*);
void SDOM_EventType__FocusLost_settarget_only(SDOM_EventType__FocusLost*, const char*);
// property: global
const char* SDOM_EventType__FocusLost_getglobal(const SDOM_EventType__FocusLost*);
void SDOM_EventType__FocusLost_setglobal(SDOM_EventType__FocusLost*, const char*);

/* Type: EventType::Quit */
typedef struct SDOM_EventType__Quit SDOM_EventType__Quit;

// property: captures
const char* SDOM_EventType__Quit_getcaptures(const SDOM_EventType__Quit*);
void SDOM_EventType__Quit_setcaptures(SDOM_EventType__Quit*, const char*);
// property: bubbles
const char* SDOM_EventType__Quit_getbubbles(const SDOM_EventType__Quit*);
void SDOM_EventType__Quit_setbubbles(SDOM_EventType__Quit*, const char*);
// property: target_only
const char* SDOM_EventType__Quit_gettarget_only(const SDOM_EventType__Quit*);
void SDOM_EventType__Quit_settarget_only(SDOM_EventType__Quit*, const char*);
// property: global
const char* SDOM_EventType__Quit_getglobal(const SDOM_EventType__Quit*);
void SDOM_EventType__Quit_setglobal(SDOM_EventType__Quit*, const char*);

/* Type: EventType::Show */
typedef struct SDOM_EventType__Show SDOM_EventType__Show;

// property: captures
const char* SDOM_EventType__Show_getcaptures(const SDOM_EventType__Show*);
void SDOM_EventType__Show_setcaptures(SDOM_EventType__Show*, const char*);
// property: bubbles
const char* SDOM_EventType__Show_getbubbles(const SDOM_EventType__Show*);
void SDOM_EventType__Show_setbubbles(SDOM_EventType__Show*, const char*);
// property: target_only
const char* SDOM_EventType__Show_gettarget_only(const SDOM_EventType__Show*);
void SDOM_EventType__Show_settarget_only(SDOM_EventType__Show*, const char*);
// property: global
const char* SDOM_EventType__Show_getglobal(const SDOM_EventType__Show*);
void SDOM_EventType__Show_setglobal(SDOM_EventType__Show*, const char*);

/* Type: EventType::Enabled */
typedef struct SDOM_EventType__Enabled SDOM_EventType__Enabled;

// property: captures
const char* SDOM_EventType__Enabled_getcaptures(const SDOM_EventType__Enabled*);
void SDOM_EventType__Enabled_setcaptures(SDOM_EventType__Enabled*, const char*);
// property: bubbles
const char* SDOM_EventType__Enabled_getbubbles(const SDOM_EventType__Enabled*);
void SDOM_EventType__Enabled_setbubbles(SDOM_EventType__Enabled*, const char*);
// property: target_only
const char* SDOM_EventType__Enabled_gettarget_only(const SDOM_EventType__Enabled*);
void SDOM_EventType__Enabled_settarget_only(SDOM_EventType__Enabled*, const char*);
// property: global
const char* SDOM_EventType__Enabled_getglobal(const SDOM_EventType__Enabled*);
void SDOM_EventType__Enabled_setglobal(SDOM_EventType__Enabled*, const char*);

/* Type: EventType::MouseWheel */
typedef struct SDOM_EventType__MouseWheel SDOM_EventType__MouseWheel;

// property: captures
const char* SDOM_EventType__MouseWheel_getcaptures(const SDOM_EventType__MouseWheel*);
void SDOM_EventType__MouseWheel_setcaptures(SDOM_EventType__MouseWheel*, const char*);
// property: bubbles
const char* SDOM_EventType__MouseWheel_getbubbles(const SDOM_EventType__MouseWheel*);
void SDOM_EventType__MouseWheel_setbubbles(SDOM_EventType__MouseWheel*, const char*);
// property: target_only
const char* SDOM_EventType__MouseWheel_gettarget_only(const SDOM_EventType__MouseWheel*);
void SDOM_EventType__MouseWheel_settarget_only(SDOM_EventType__MouseWheel*, const char*);
// property: global
const char* SDOM_EventType__MouseWheel_getglobal(const SDOM_EventType__MouseWheel*);
void SDOM_EventType__MouseWheel_setglobal(SDOM_EventType__MouseWheel*, const char*);

/* Type: EventType::EnterFullscreen */
typedef struct SDOM_EventType__EnterFullscreen SDOM_EventType__EnterFullscreen;

// property: captures
const char* SDOM_EventType__EnterFullscreen_getcaptures(const SDOM_EventType__EnterFullscreen*);
void SDOM_EventType__EnterFullscreen_setcaptures(SDOM_EventType__EnterFullscreen*, const char*);
// property: bubbles
const char* SDOM_EventType__EnterFullscreen_getbubbles(const SDOM_EventType__EnterFullscreen*);
void SDOM_EventType__EnterFullscreen_setbubbles(SDOM_EventType__EnterFullscreen*, const char*);
// property: target_only
const char* SDOM_EventType__EnterFullscreen_gettarget_only(const SDOM_EventType__EnterFullscreen*);
void SDOM_EventType__EnterFullscreen_settarget_only(SDOM_EventType__EnterFullscreen*, const char*);
// property: global
const char* SDOM_EventType__EnterFullscreen_getglobal(const SDOM_EventType__EnterFullscreen*);
void SDOM_EventType__EnterFullscreen_setglobal(SDOM_EventType__EnterFullscreen*, const char*);

#ifdef __cplusplus
}
#endif

#define SDOM_CAPI_VERSION "generated"

#endif // SDOM_CAPI_OBJECTS_H
