/* Generated by SDOM DataRegistry */
#ifndef SDOM_CAPI_OBJECTS_H
#define SDOM_CAPI_OBJECTS_H

#ifdef __cplusplus
extern "C" {
#endif

/* Type: UT_TestType */
typedef struct SDOM_UT_TestType SDOM_UT_TestType;


#ifdef __cplusplus
}
#endif

#define SDOM_CAPI_VERSION "generated"

#endif // SDOM_CAPI_OBJECTS_H
